### PR TITLE
Upgrade version will be in modules directory

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr Hracek phracek@redhat.com

### CODE REVIEW

**Comment by bocekm** [comment]
Can one of the admins verify this patch?

**Comment by bocekm** [comment]
[test]

**Comment by bocekm** [comment]
[test]

**Comment by bocekm** [comment]
[test]

**Comment by phracek** [comment]
Have you ever have time to look at this? This Pull Request is a bit urgent. Upgrade path in the name of module directory 'really' does not make sense.

**Comment by pirat89** [comment]
@phracek Could you make this compatible with master? I can't promise anything this month,

**Comment by bocekm** [comment]
Superseded by https://github.com/upgrades-migrations/preupgrade-assistant/pull/233

**Pull request closed without merging**
