### PR TITLE
Binary_req checker during module generation

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr Hracek phracek@redhat.com

### CODE REVIEW

**Comment by bocekm** [comment]
Can one of the admins verify this patch?

**Comment by AloisMahdal** [comment]
What is this PR trying to achieve?

Checking binary_req during build time does not make a lot of sense to me...

**Comment by bocekm** [comment]
ok to test

**Comment by bocekm** [comment]
[test[

**Comment by bocekm** [comment]
[test]

**Comment by bocekm** [comment]
[test]

**Comment by bocekm** [comment]
@phracek, can you please provide some info about this update? I thought that _binary_req_ in INI is there to tell what binaries are required **during assessment**. The code around this change is not much self-explanatory so I'm not exactly sure what it's supposed to be doing, but it seems that this change adds a check whether the binaries are present during generating OpenSCAP XMLs by _preupg-content-creator_, which is something we shouldn't be doing.
Perhaps @pirat89 might also weigh in.

**Comment by phracek** [comment]
Closing the issue. This is a part for preupg-lint checker.

**Pull request closed without merging**
