### PR TITLE
Remove unknown exit value

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr Hracek phracek@redhat.com

### CODE REVIEW

**Comment by bocekm** [comment]
Can one of the admins verify this patch?

**Comment by bocekm** [comment]
ok to test

**Comment by bocekm** [comment]
add to whitelist

**Comment by phracek** [comment]
This Pull Request should be ready for Review. Bugzilla for modules already exists https://bugzilla.redhat.com/show_bug.cgi?id=1375185

**Comment by phracek** [comment]
The last think which should be checked is if preupg works even if UNKNOWN value is reported by module like XCCDF_RETURN_VALUE_UNKNOWN. This is officially supported by OpenSCAP.

**Comment by bocekm** [comment]
[test]

**Comment by bocekm** [comment]
Please remove also line [*os.environ['XCCDF_RESULT_UNKNOWN'] = "2"* from tests/\_\_init\_\_.py](https://github.com/upgrades-migrations/preupgrade-assistant/blob/remove_unknown/tests/__init__.py#L23)

**Comment by bocekm** [comment]
[test]

**Pull request merged**
