### PR TITLE
WIP: Support RHEL 6.6

### LINKED ISSUE #322: Support RHEL 6.6 (RHEL 6.7+ is supported now)
**Fix the error:**
```
File "/usr/lib/python2.6/site-packages/preupg/utils.py", line 537, in config_has_section
  config = configparser.RawConfigParser(allow_no_value=True)
TypeError: __init__() got an unexpected keyword argument 'allow_no_value'
```

**Update the Requires in spec to:**
```
openscap%{?_isa} >= 0:1.0.8
openscap-engine-sce%{?_isa} >= 0:1.0.8
openscap-utils%{?_isa} >= 0:1.0.8
```

**Get rid of python-six**
python-six is not provided on RHEL 6.6

### PR DESCRIPTION
**Pull request by pirat89**
PA should support RHEL 6.6 for assessment of the system. Current state:

- [x] get rid of python-six (missing on RHEL 6.6)
- [x] update requirements in spec
- [x] resolve troubles with RawConfigParser (see #322)

Resolves #322

### CODE REVIEW

**Comment by pirat89** [comment]
Note: I was thinking about method is `SystemIdentification` clast like that:
```python
    @staticmethod
    def get_rhel_version():
        """Returns tuple with major and minor version of RHEL or None."""
        if SystemIdentification.get_variant() is None:
            return None
        redhat_release = FileHelper.get_file_content("/etc/redhat-release", "rb")
        return tuple([int(x) for x in redhat_release.split()[6].split(".")])

```

But to be used already at least once, the class had to be indeprendent on `FileHelper` and has to be defined before `configparser` is imported in the file. For now, I used solution that you can see in the third commit.

**Comment by pirat89** [comment]
@AloisMahdal: Lojzo, for testing purposes:
- should be possible to install preupgrade-assistant without broken dependencies
- assessment is possible on RHEL 6.6 without errors generated by PA itself.

**Comment by AloisMahdal** [comment]
`qa_ack`: Just run preupgrade-assistant test suite on RHEL-6.6 (`ipu tier pa=P356 pa-* > p356.sh; edit p356.sh; sh p356.sh`).  (Watch for, and fix any incompatibilities caused by test suite itself.)

**Comment by AloisMahdal** [comment]
> Watch for, and fix any incompatibilities caused by test suite itself

for example, old openscap merges stdout and stderr from `check` script, so `preupgrade_assistant__run1` will trigger "stray output" false-positive with any risk.  IOW, we need to update test library prior to any testing.

**Comment by bertinatto** [comment]
@AloisMahdal, after discussing a96c9fe with @bocekm and @mfranczy, we decided to try an alternative approach. This is reflected on PR #359.

I don't seem to be able to set the correct tags there, so I'll ask you here: is it possible to perform the checks of that PR instead of this one?

Thanks.

**Comment by AloisMahdal** [comment]
Acked the other one.  Since both PRs are doing the same change from user POV, we can test the other one with exactly the same test procedure.

**Comment by bocekm** [comment]
This PR has been obsoleted by https://github.com/upgrades-migrations/preupgrade-assistant/pull/359.

**Pull request closed without merging**
