### PR TITLE
Fix logs and additional output in result file

### PR DESCRIPTION
**Pull request by pirat89**
**_result.xml_ tweaks:**
- Removed whitespace at the beginning and end of each module _stdout_ and _stderr_ (Additional info` and `Logs`).
- _stdout_ of modules is removed from the  _result.xml_ when it is empty, however _stderr_ wasn't. Now both of them are removed when empty.

**Simple style _result.html_ tweaks:**
- _stdout_ and _stderr_ are now left in the report no matter what the result of a module is. Before the output was not shown for `pass` and `fixed` results. The behaviour is now consistent with the complex report style.
- Remove an excessive newline from the beginning of each module _stdout_ and _stderr_ (`Additional info` and `Logs`).

### CODE REVIEW

**Comment by bocekm** [comment]
[test]

**Comment by pirat89** [comment]
@mbocek: please, do NOT merge it yet. Lojza has some compliance with this which seems relevant maybe. It should be discussed yet.

**Comment by bocekm** [comment]
After discussion with @AloisMahdal, the trimming of whitespaces should be less intrusive - trim at maximum empty lines (lines with whitespaces only).

**Comment by AloisMahdal** [comment]
Actually, according to my observation on RHEL5, only text that gets added is:

 *  `0x0a` before the data,
 *  `0a:0a:20:20:20:20:20:20:20:20:20:20:0a` after the data.

That is, something along these lines should be fine:

    if data.startswith('\n') and data.endswith('\n\n          \n'):
        data = data[1:-13]

OTOH, similar issue has been also observed on RHEL6 (reported last summer as rhbz#1362718) but openscap has been updated since then so I'm not sure if it still applies.

**Comment by bocekm** [comment]
Rebased with master and changed the whitespace stripping per @AloisMahdal recommendation.

**Comment by bocekm** [comment]
@pirat89 I've made changes to the pull request. Because you're the PR author so you can't do the review but please take a look at my commit and if it's ok with you, let me know, and I'll approve the PR.

**Comment by pirat89** [comment]
--test--

**Comment by pirat89** [comment]
--test--

**Comment by pirat89** [comment]
--test--

**Comment by bocekm** [comment]
@pirat89, I've made changes to the pull request. You're the PR author so you can't officially do the review. But please, take a look at my commit and if it's ok with you I'll approve the PR.

**Comment by pirat89** [comment]
@mbocek: It removes empty grey blocks from the report, but non-empty blocks (logs) still contain the empty first line. It is because of newline character after the `<code>` tag:

```xhtml
<code>
text
</code>
```

It should be one of these:
```xhtml
<!-- first solution -->
<code>text</code>
<!-- second solution -->
<code>text
</code>
```

But from my point of view it is not blocking, as the empty blocks have been the most annoying.

**Comment by bocekm** [comment]
@pirat89, I fixed that - now there's no excessive newline for the stdout/stderr.
Also I changed the simple (old) style report so it now displays _stdout_ and _stderr_ in the report no matter what the result of a module is. Before the output was not shown for `pass` and `fixed` results. The behaviour is now consistent with the complex report style.
Please verify it works. Thanks.

**Comment by pirat89** [comment]
It works as I see :-)

**Pull request merged**
