### PR TITLE
Remove kickstart CLI option

### PR DESCRIPTION
**Pull request by MajoDurco**
Remove --kickstart option, preupg-kickstart-generator tool has the same
functionality

### CODE REVIEW

**Comment by AloisMahdal** [comment]
Acking, simple check: just make sure the option is gone from help, man page and the code.

**Comment by bocekm** [comment]
@pirat89, @MajoDurco: I made one change. Please check it and if you're OK with it, I'll merge this PR to master.

**Comment by pirat89** [comment]
Yes it make sense.

**Comment by MajoDurco** [comment]
Seems fine to me.

**Pull request merged**
