### PR TITLE
Script for testing Python and/or Bash modules

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr Hracek phracek@redhat.com

### CODE REVIEW

**Comment by phracek** [comment]
This Pull Request will solve an issues #146

**Comment by bocekm** [comment]
Can one of the admins verify this patch?

**Comment by bocekm** [comment]
ok to test

**Comment by bocekm** [comment]
[test]

**Comment by phracek** [comment]
This will be solved by redesigning content creation and wrappers around scripts.
Each module will have stored information like current directory, mode etc.

**Pull request closed without merging**
