### PR TITLE
Remove creation of admin and user reports

### PR DESCRIPTION
**Pull request by MajoDurco**
result-admin.xml/html, result-user.xml/html are reduntant in PA because
the final result is the same as in the default result.xml/html

### CODE REVIEW

**Comment by bocekm** [comment]
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1414322

**Comment by AloisMahdal** [comment]
IIRC, there was also an element in UI that mentioned these reports; I guess chage might be necessary there as well. (But I might be wrong...)

**Comment by AloisMahdal** [comment]
Ack for next cycle; this will be really easy to add to in downstream suite (preupg/result-files test), plus we'll verify the UI, which should also pretty straightforward.

**Comment by bocekm** [comment]
@MajoDurco, I guess the code here https://github.com/upgrades-migrations/preupgrade-assistant/blob/remove_admin_report/preupg/xmlgen/xml_utils.py#L321 can be removed too.

**Comment by AloisMahdal** [comment]
`qa_verified`: Already added to downstream test suite and verified as part of previous release.

**Pull request merged**
